### PR TITLE
Implemented IDisposable properly + call .Flush() on Dispose

### PR DESCRIPTION
**Pull request by jbattermann**
.. and updated Readme.md to explain all of this (see also #9)

### CODE REVIEW

**Comment by palmtech** [comment]
A "proper" implementation of the Dispose pattern is superfluous here, a sink will have it's Dispose method called only by Serilog; that's the only mechanism you need to consider. The simpler implementation is perfectly adequate. May I suggest you have a look at how some of the other sinks have been written, such as Seq and Splunk.

**Comment by nblumhardt** [comment]
Dispose implementation aside, does this cover your scenario @palmtech?

It sounds like we're between a rock and a hard place with respect to the app insights APIs; going this route at least it's certain that if you care about flushing the buffer you don't have to worry about a slow flush still causing event loss (or extending the `Sleep()` to cover nth percentile response times).

:+1: from me, unless I'm missing any details. Cheers @jbattermann !

**Comment by palmtech** [comment]
@nblumhardt, I'm not terribly keen on this implementation because it requires sink specific code moved outside of the serilog configuration.  Ie, rather than use Log.CloseAndFlush(), I have to maintain sink specific code at exit points in the application. It also means that I can't use .ReadFrom.AppSettings() to keep my application sink agnostic.  This data loss issue isn't an edge case, it's going to be encountered by every person that attempts to use .WriteTo.ApplicationInsightsTraces(key). I'd rather have the simplest configuration "just work", or at least a parameter that could set the sleep.

**Comment by jbattermann** [comment]
@palmtech just to get this out of the way - all your input and PRs were and _are_ highly appreciated - really.. 

This PR is not meant to ignore or override yours, but to provide an _alternative_ that merely performs the .Flush() on .Dispose().

Maybe the wording of 'implemented interface _properly_' came across a bit weird... again - not meant to to sound better or worse than your #9 .. that's absolutely not what this discussion is about.

This sink is used by others besides you and me but as a library it cannot control a process' lifetime and block a thread, be it optional or not.

Certainly most/all users do expect that all messages logged end up in AI and if they don't, are certainly confused why they didn't show up but they would be equally confused why their UI thread freezes entirely for a second if .CloseAndFlush() / .Dispose() was called on that one, or a mobile application or windows service gets terminated because it went past its OS given graceful shutdown time etc.
And the time required for the .Flush() to fully propagate the data to AI will always depend on similar application-specific constraints - a mobile application used in the middle of nowhere with a GSM/Edge connection will take longer than 1000ms for > 3kb of data.. and so would a burst of log messages in a very short amount of time for a very fast connected system, too.

So because -Application Insights- does not handle this properly from our perspective, yours and mine, the sink's users will _always_ have to make a conscious decision either way regarding

- _if_ to wait (_never_ stopping applications or applications that take a long time to shutdown "anyway" probably won't care.. even though they should, too)

- _how long_ to wait and also

- _how_  to wait (`Thread.Sleep()`, `await Task.Delay()`, ...).

There's no golden bullet here, there really isn't, but these variables can only be answered by each user / developer using this sink for every application specifically.

While we could add more parameters to the sink regarding the '_if_' and the '_how long_' to wait, the sink could not provide alternatives for _how_ to wait in .Dispose() - so the sink would force a blocking, sleeping thread on the application or litter the interface even more with a more flexible(?) / complex solution.

Now one could argue that one could circumvent that by logging asynchronously in a separate logger thread anyway, or call CloseAndFlush() in a separate thread - but that is quite non-obvious and pollute the application's design.

If one day Serilog's Core would provide and use a common `.Flush(int timeout)` / `.FlushAsync(int timeout, CancellationToken cancellationToken = default(CancellationToken)` interface if implemented by the Sinks I'll certainly revisit this / your issue but for now this Sink does all a Serilog Sink can do - with this PR (and your original #9 sans the .Sleep()) it will .Flush() and therefore align with other Sinks (implementation details aside).


Applications using the sink will have no runtime impact when updating to the new version that includes the code & the Readme now explains what is and has always been going on - by the AI library and explains that devs might want to .Delay() / .Sleep() or whatnot. But that sleep / delay is not sink specific - it's AI specific.

It's a compromise and as such not ideal.

**Pull request merged**
