### PR TITLE
added dnx core version

### PR DESCRIPTION
**Pull request by alexvaluyskiy**
Added support for Net Core.

Todo:
- ~~update build script~~
- switch to .Net Platform instead of dnxcore50, when Microsoft.ApplicationInsights 2.0 supports it.

### CODE REVIEW

**Comment by jbattermann** [comment]
Woohoo - nice! :+1:

**Comment by nblumhardt** [comment]
Excellent! Should we drop an `appveyor.yml` file into this so that build changes go in with the merge? I can grab one with current settings (including encrypted publish keys etc) if that sounds like a plan...

**Comment by ravengerUA** [comment]
Yes, we should put appveyor.yml here.

Also I have problems with this file in this pull request 
https://github.com/serilog/serilog-sinks-elasticsearch/pull/21

**Comment by nblumhardt** [comment]
```yml
version: '{build}'
build_script:
- ps: ./Build.ps1 -majorMinor "2.0" -patch "$env:APPVEYOR_BUILD_VERSION" -customLogger "C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
artifacts:
- path: Serilog.*.nupkg
deploy:
- provider: NuGet
  api_key:
    secure: nvZ/z+pMS91b3kG4DgfES5AcmwwGoBYQxr9kp4XiJHj25SAlgdIxFx++1N0lFH2x
  on:
    branch: master
```

**Comment by nnyegaard** [comment]
A merge would be awesome, so it could be used with RC1.

**Comment by jbattermann** [comment]
LGTM :+1: However, would it make sense to also add / support dnxcore50 as AI 2.0 RC-1 etc does .. for now and for this PR.. and whenever / however the MS AI API & NuGet package changes over time.. or serilog itself does, revisit .Net platform compatibility?

**Comment by nnyegaard** [comment]
I would take it incremental. So release a beta package for RC1, then when the ASP.NET team make a new public release, release a new beta version, targeting that. 

This should of course not be to hard to make the changes between the releases (And I don't think it will).

**Pull request closed without merging**
