### PR TITLE
Add support for .NET Core

### PR DESCRIPTION
**Pull request by flagbug**
- Switch the project system to project.json
- Change the target framework to netstandard1.3

I'm not familiar with the build system, so I haven't changed that in this PR, maybe someone else can do this?

I hope these changes are OK for the maintainers, let me know if I should do anything differently!

### CODE REVIEW

**Comment by jbattermann** [comment]
Nice! Thanks @flagbug  - I'll have a look later tonight but the only thing I saw at first glance was that the project was set to .Net 4.5.2 (instead of previously 4.5) - is that on purpose / mandatory for the switch over to .Net Core or can we leave it at 4.5?

Regarding build .. hrmm.. @nblumhardt you had some scripts regarding that as far as I remember (I saw them pop up in the previous dnx PR that got closed).. would/could you maybe chime in here as I don't know the specifics myself.

**Comment by flagbug** [comment]
>  I'll have a look later tonight but the only thing I saw at first glance was that the project was set to .Net 4.5.2 (instead of previously 4.5) - is that on purpose / mandatory for the switch over to .Net Core or can we leave it at 4.5?

I think that's just Visual Studio doing it's thing, but looking at it again, `netstandard1.3` only support .NET 4.6 and upwards, so I'll have to create a separate net45 target!

**Comment by nblumhardt** [comment]
Great, good to see this moving forwards :-)

To cut a long story short, you should be able to copy:

 * _appveyor.yml_
 * _Build.ps1_
 * _global.json_

From the root of the Serilog repository here: https://github.com/serilog/serilog and drop them into the root of this repository unchanged.

Then, by running:

```
powershell ./Build.ps1
```

from a command prompt in the repository root, a package tagged `-{branchname}-local` should pop out in /artifacts.

We're trying to standardise on this build structure across the Serilog repos, so let me know if any changes are needed.

Cheers!

**Comment by flagbug** [comment]
@nblumhardt Done! Not sure what to do about the version in `project.json`, can anyone have a look at this?

**Comment by jbattermann** [comment]
2.0-* is correct for the moment.. yeah - the final/complete package etc version is set / updated during the CI build then.

So yep - I think it all looks might fine, thanks!! :+1:

**Comment by nblumhardt** [comment]
Almost! The version needs to be three-part, so `2.1.0-*` would probably be the best bet (given the current version on NuGet is `2.0.56`).

**Comment by nblumhardt** [comment]
(BTW, for other sinks I've converted recently, I've just added an empty test project - it makes it easier for tests to be included in PRs and so-on, even when there's nothing currently there.)

**Comment by flagbug** [comment]
> Almost! The version needs to be three-part, so 2.1.0-* would probably be the best bet (given the current version on NuGet is 2.0.56).

Done!

**Pull request merged**
